export const Majors = ['Please select your major...', 'Accounting ', 'Actuarial Science ', 'Aeronautical and Astronautical Engineering ', 'Aeronautical Engineering Technology ',
    'Aerospace Financial Analysis ', 'African American Studies ', 'Agribusiness (multiple concentrations) ', 'Agricultural Communication ',
    'Agricultural Economics (multiple concentrations) ', 'Agricultural Education ', 'Agricultural Engineering (College of Agriculture) ',
    'Agricultural Engineering (College of Engineering) ', 'Agricultural Systems Management ', 'Agronomy ', 'Airline Management and Operations ',
    'Airport Management and Operations ', 'American Studies ', 'Animal Sciences (multiple concentrations) ', 'Animation and Visual Effects  ',
    'Anthropology ', 'Applied Meteorology and Climatology ', 'Aquatic Sciences ', 'Art History ', 'Artificial Intelligence ',
    'Artificial Intelligence (College of Science) ', 'Asian Studies ', 'Atmospheric Science/Meteorology ', 'Audio Engineering Technology ',
    'Automation and Systems Integration Engineering Technology ', 'Aviation Management ', 'Biochemistry ', 'Biochemistry (Chemistry) ',
    'Biological Engineering (College of Agriculture) ', 'Biological Engineering (College of Engineering) ', 'Biology ', 'Biomedical Engineering ',
    'Biomedical Health Sciences ', 'Brain and Behavioral Sciences ', 'Building Information Modeling ', 'Business Analytics and Information Management ',
    'Cell, Molecular, and Developmental Biology ', 'Chemical Biology and Biochemistry ', 'Chemical Engineering ', 'Chemistry ',
    'Chemistry - American Chemical Society ', 'Chinese Studies ', 'Civil Engineering ', 'Classical Studies ', 'Communication (multiple concentrations) ',
    'Comparative Literature ', 'Computer and Information Technology ', 'Computer Engineering ', 'Computer Engineering Technology ',
    'Computer Infrastructure & Network Engineering Technology ', 'Computer Science  ', 'Computing Systems Analysis and Design ',
    'Construction Engineering  and Management ', 'Construction Management Technology ', 'Creative Writing ', 'Crop Science ', 'Cybersecurity ',
    'Data Analytics, Technologies and Applications ', 'Data Science ', 'Data Visualization ', 'Design and Construction Integration  ',
    'Developmental and Family Science ', 'Digital Criminology ', 'Digital Enterprise Systems ', 'Early Childhood Education and Exceptional Needs ',
    'Ecology, Evolution, and Environmental Sciences ', 'Economics (Pre) (College of Liberal Arts) ', 'Economics (Daniels School of Business) ',
    'Electrical Engineering ', 'Electrical Engineering Technology ', 'Elementary Education ', 'Energy Engineering Technology ', 'Engineering (First Year) ',
    'Engineering / Technology Teacher Education ', 'English ', 'Environmental and Ecological Engineering ',
    'Environmental & Natural Resources Engineering (College of Agriculture) ', 'Environmental & Natural Resources Engineering (College of Engineering) ',
    'Environmental Geosciences ', 'Exploratory Studies (for undecided students) ', 'Family and Consumer Sciences Education ', 'Farm Management ',
    'Fermentation Science ', 'Film and Video ', 'Finance ', 'Financial Counseling and Planning ', 'Flight (Professional Flight Technology) ',
    'Food Science ', 'Forestry ', 'French ', 'Game Development and Design ', 'General Education: Curriculum and Instruction (non-licensure) ',
    'General Education: Educational Studies (non-licensure) ', 'Genetics ', 'Geology and Geophysics ', 'German ', 'Global Studies ', 'Health and Disease ',
    'History ', 'Horticulture (multiple concentrations) ', 'Hospitality and Tourism Management ', 'Human Resource Development ', 'Human Services ',
    'Inclusion: Dual License in Special Education (K-6) & Elementary Education ', 'Industrial Design ', 'Industrial Engineering ',
    'Industrial Engineering Technology ', 'Insect Biology ', 'Integrated Business and Engineering ', 'Integrated Studio Arts, BFA (Portfolio Required) ',
    'Interdisciplinary Engineering Studies ', 'Interior Architecture ', 'Interior Design - Professional Program ', 'Italian Studies ', 'Japanese ',
    'Jewish Studies ', 'Kinesiology ', 'Landscape Architecture (Pre) ', 'Law and Society (Criminology) ', 'Linguistics ', 'Management (General) ',
    'Marketing ', 'Materials Engineering ', 'Mathematics ', 'Mathematics, Applied ', 'Mathematics - Business ', 'Mathematics Education ',
    'Mathematics - Statistics ', 'Mechanical Engineering ', 'Mechanical Engineering Technology ', 'Mechatronics Engineering Technology  ',
    'Medical Laboratory Sciences ', 'Microbiology ', 'Motorsports Engineering ', 'Multidisciplinary Engineering ', 'Music  ',
    'Natural Resources and Environmental Science (multiple concentrations) ', 'Neurobiology and Physiology ', 'Nuclear Engineering ', 'Nursing ',
    'Nutrition and Dietetics ', 'Nutrition and Dietetics/Nutrition, Fitness, and Health (double major) ', 'Nutrition, Fitness, and Health ',
    'Nutrition Science ', 'Occupational and Environmental Health Sciences ', 'Organizational Leadership ', 'Pharmaceutical Sciences ', 'Philosophy ',
    'Physics ', 'Physics, Applied ', 'Planetary Sciences ', 'Plant Genetics, Breeding, and Biotechnology ', 'Plant Science  ',
    'Plant Studies - Exploratory (Pre) ', 'Political Science ', 'Pre-dentistry ', 'Pre-law ', 'Pre-medicine ', 'Pre-occupational Therapy ',
    'Pre-physical Therapy ', 'Pre-physician Assistant ', 'Pre-veterinary Medicine ', 'Professional Writing ', 'Psychological Sciences ', 'Public Health  ',
    'Purdue Polytechnic Institute Statewide Programs ', 'Radiological Health Sciences ', 'Religious Studies ', 'Retail Management ',
    'Robotics Engineering Technology  ', 'Russian ', 'Sales and Marketing ', 'Science Education (Biology, Chemistry, Earth/Space, Physics) ',
    'Selling and Sales Management ', 'Smart Manufacturing Industrial Informatics ', 'Social Studies Education ', 'Sociology ', 'Soil and Water Sciences ',
    'Sound for the Performing Arts (Portfolio Required) ', 'Spanish ', 'Special Education: Mild & Intense Intervention 5-12 ',
    'Special Education: Mild & Intense Intervention K-6 ', 'Speech, Language, and Hearing Sciences ', 'Statistics, Applied ',
    'Statistics with Mathematics Option ', 'Studio Arts and Technology ', 'Supply Chain and Operations Management ',
    'Supply Chain & Sales Engineering Technology ', 'Sustainable Food and Farming Systems ', 'Theatre ', 'Turf Management and Science ',
    'Unmanned Aerial Systems ', 'UX Design ', 'Veterinary Nursing ', 'Visual Arts Design Education ', 'Visual Arts Education ',
    'Visual Communication Design (Graphic Design) ', 'Web Programming and Design ', 'Wildlife ', 'Women’s, Gender  and Sexuality Studies ']